openapi: 3.2.0
info:
  version: '2023-07-19'
  x-release: v4
  title: AWS Health Imaging List DICOM Import Jobs API
  description: This is the AWS HealthImaging API Reference.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: medical-imaging
  x-aws-signingName: medical-imaging
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/medical-imaging-2023-07-19.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://medical-imaging.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Health Imaging multi-region endpoint
- url: https://medical-imaging.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Health Imaging multi-region endpoint
- url: http://medical-imaging.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Health Imaging endpoint for China (Beijing) and China (Ningxia)
- url: https://medical-imaging.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Health Imaging endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: List DICOM Import Jobs
paths:
  /listDICOMImportJobs/datastore/{datastoreId}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListDICOMImportJobs
      description: List import jobs created by this AWS account for a specific data store.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDICOMImportJobsResponse'
        '480':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '481':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '483':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '484':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '485':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
      parameters:
      - name: datastoreId
        in: path
        required: true
        description: The data store identifier.
        schema:
          type: string
          pattern: '[0-9a-z]{32}'
      - name: jobStatus
        in: query
        required: false
        description: The filters for listing import jobs based on status.
        schema:
          type: string
          enum:
          - SUBMITTED
          - IN_PROGRESS
          - COMPLETED
          - FAILED
      - name: nextToken
        in: query
        required: false
        description: The pagination token used to request the list of import jobs on the next page.
        schema:
          type: string
          pattern: \p{ASCII}{0,8192}
          minLength: 1
          maxLength: 8192
      - name: maxResults
        in: query
        required: false
        description: The max results count. The upper bound is determined by load testing.
        schema:
          type: integer
          minimum: 1
          maximum: 50
      summary: Amazon HealthImaging List DICOM Import Jobs
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - List DICOM Import Jobs
components:
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  schemas:
    RoleArn:
      type: string
      pattern: arn:aws(-[^:]+)?:iam::[0-9]{12}:role/.+
      minLength: 20
      maxLength: 2048
    Message:
      type: string
      pattern: '[\w -:]+'
      minLength: 1
      maxLength: 2048
    JobId:
      type: string
      pattern: '[0-9a-z]+'
      minLength: 1
      maxLength: 32
    ConflictException: {}
    InternalServerException: {}
    ValidationException: {}
    JobStatus:
      type: string
      enum:
      - SUBMITTED
      - IN_PROGRESS
      - COMPLETED
      - FAILED
    DICOMImportJobSummary:
      type: object
      required:
      - jobId
      - jobName
      - jobStatus
      - datastoreId
      properties:
        jobId:
          allOf:
          - $ref: '#/components/schemas/JobId'
          - description: The import job identifier.
        jobName:
          allOf:
          - $ref: '#/components/schemas/JobName'
          - description: The import job name.
        jobStatus:
          allOf:
          - $ref: '#/components/schemas/JobStatus'
          - description: The filters for listing import jobs based on status.
        datastoreId:
          allOf:
          - $ref: '#/components/schemas/DatastoreId'
          - description: The data store identifier.
        dataAccessRoleArn:
          allOf:
          - $ref: '#/components/schemas/RoleArn'
          - description: The Amazon Resource Name (ARN) that grants permissions to access medical imaging resources.
        endedAt:
          allOf:
          - $ref: '#/components/schemas/Date'
          - description: The timestamp when an import job ended.
        submittedAt:
          allOf:
          - $ref: '#/components/schemas/Date'
          - description: The timestamp when an import job was submitted.
        message:
          allOf:
          - $ref: '#/components/schemas/Message'
          - description: The error message thrown if an import job fails.
      description: Summary of import job.
    ThrottlingException: {}
    JobName:
      type: string
      pattern: '[A-Za-z0-9._/#-]+'
      minLength: 1
      maxLength: 64
    ResourceNotFoundException: {}
    Date:
      type: string
      format: date-time
    AccessDeniedException: {}
    DICOMImportJobSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DICOMImportJobSummary'
    ListDICOMImportJobsResponse:
      type: object
      required:
      - jobSummaries
      properties:
        jobSummaries:
          allOf:
          - $ref: '#/components/schemas/DICOMImportJobSummaries'
          - description: A list of job summaries.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The pagination token used to retrieve the list of import jobs on the next page.
    NextToken:
      type: string
      pattern: \p{ASCII}{0,8192}
      minLength: 1
      maxLength: 8192
    DatastoreId:
      type: string
      pattern: '[0-9a-z]{32}'
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/medical-imaging/
x-hasEquivalentPaths: true
